name: 'Tomles'
description: 'Update some yaml!'
inputs:
  package: # go package to update.
    description: 'go package of dep to udpate'
    required: true
  branch:
    description: 'set to this branch'
    required: false
  version:
    description: 'set to this version'
    required: false
  revision:
    description: 'set to this revision'
    required: false

outputs:
  output:
    description: 'The output of tomles run'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "update"
    - "${{ inputs.package }}"
    - "--revision=${{ inputs.revision }}"
    - "--branch=${{ inputs.branch }}"
    - "--version=${{ inputs.version}}"
    - "--filename=/workspace/source/Gopkg.toml"
    - "--verbose"